<a href="https://colab.research.google.com/github/krishbhowmick/IITB_DataScienceTraining/blob/main/IITB1_1_python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 1471-D09A

 Directory of C:\Users\Shubh_Ram\ML_IITB

07/09/2020  08:53 PM    <DIR>          .
07/09/2020  08:53 PM    <DIR>          ..
07/09/2020  08:53 PM    <DIR>          .ipynb_checkpoints
07/09/2020  08:52 PM                72 test_python_1.ipynb
               1 File(s)             72 bytes
               3 Dir(s)  82,993,192,960 bytes free


In [ ]:
pwd

'C:\\Users\\Shubh_Ram\\ML_IITB'

In [ ]:
print("iitb")

iitb


### python obj

1. list []
2.tuple ()
3.dict {}
4.bool 0,1
5.set {}

In [ ]:
a="chandan"

In [ ]:
print(type(a))

<class 'str'>


In [ ]:
#list 

In [ ]:
a=[11,12,13,14,15]

In [ ]:
print(type(a))

<class 'list'>


In [ ]:
a[0]

11

In [ ]:
len(a)

5

In [ ]:
a[len(a)-1]

15

In [ ]:
a[-1]

15

In [ ]:
a[-2]

14

In [ ]:
list(range(2,5))

[2, 3, 4]

In [ ]:
list(range(1,10,3))

[1, 4, 7]

In [ ]:
my_lsit=list(range(1,10000,1))

#my_lsit
start=time.time()
for i in range(len(my_lsit)):
    print(my_lsit[i])
end=time.time()
print("Time taken by for operator is {} second".format(end-start))

In [ ]:
import time 

start=time.time()
print(my_lsit[:])
end=time.time()
print("Time taken by : operator is {} second".format(end-start))

1.7009913921356201/ 0.0029954910278320312

In [ ]:
mylist=list(range(1,25,3))

In [ ]:
mylist[:]

[1, 4, 7, 10, 13, 16, 19, 22]

In [ ]:
mylist[:-2]

[1, 4, 7, 10, 13, 16]

In [ ]:
mylist[2:-1]

[7, 10, 13, 16, 19]

In [ ]:
mylist[::2]

[1, 7, 13, 19]

In [ ]:
mylist[::-2]

[22, 16, 10, 4]

In [ ]:
mytuple=(1, 4, 7, 10, 13, 16, 19, 22)

In [ ]:
type(mytuple)

tuple

In [ ]:
mytuple

(1, 4, 7, 10, 13, 16, 19, 22)

In [ ]:
#ADD ONE VALUE AT END (APPEND)

In [ ]:
mylist.append(20)

In [ ]:
mylist

[1, 4, 7, 10, 13, 16, 19, 22, 20]

In [ ]:
mytuple.append(20)

AttributeError: ignored

# NUMPY

In [ ]:
#FAST" CYTHON

In [ ]:
import numpy as np

In [ ]:
# ID array

In [ ]:
array_1d=np.array([1, 4, 7, 10, 13, 16, 19, 22, 20])

In [ ]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [ ]:
array_1d.ndim

1

In [ ]:
array_1d.dtype

dtype('int64')

In [ ]:
array_1d.shape

(9,)

In [ ]:
len(array_1d)

9

In [ ]:
array_1d.size

9

In [ ]:
array_1d[0]

1

In [ ]:
array_1d[:-1]

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [ ]:
# 2d

In [ ]:
list_2d=np.array([[11,12,13],[14,15,16],[17,18,19]])

In [ ]:
list_2d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
list_2d.ndim

2

In [ ]:
list_2d[0,0]

11

In [ ]:
list_2d[2,2]

19

In [ ]:
list_2d.sum()

135

In [ ]:
list_2d.sum(axis=1)

array([36, 45, 54])

In [ ]:
list_2d.sum(axis=0)

array([42, 45, 48])

In [ ]:
list_2d.shape # row and col

(3, 3)

In [ ]:
list_2d.size # total number elemets

9

In [ ]:
len(list_2d) # number row in col

3

In [ ]:
# slicing with 2d

In [ ]:
list_2d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
#[11,12,13]

In [ ]:
list_2d[:,:]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
list_2d[1:,:2]

array([[14, 15],
       [17, 18]])

In [ ]:
list_2d[0:2,1:]

array([[12, 13],
       [15, 16]])

In [ ]:
list_2d[0:3:2,0:3:2]

array([[11, 13],
       [17, 19]])

In [ ]:
list_2d[::2,::2]

array([[11, 13],
       [17, 19]])

In [ ]:
list_2d[::-1,::-1]

array([[19, 18, 17],
       [16, 15, 14],
       [13, 12, 11]])

In [ ]:
list_2d.diagonal()

array([11, 15, 19])

In [ ]:
list_2d.argmin()

0

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
list_2d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:

array_1d

array([ 1,  4,  7, 10, 13, 16, 19, 22, 20])

In [ ]:
array_1d[:-2]

array([ 1,  4,  7, 10, 13, 16, 19])